version: '3.8'
services:
    db:
        image: postgres:latest
        restart: always
        ports:
            - '5432:5432'
        volumes:
            - db:/var/lib/postgresql/data
        environment:
            - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
            - "POSTGRES_USER=${POSTGRES_USER}"
            - "POSTGRES_DB=${POSTGRES_DB}"
    redis:
        image: 'redis:alpine'
        ports:
            - '6379:6379'
    bot:
        build: .
        ports:
            - '8080:8080'
        environment:
            - NODE_ENV=production
        depends_on:
            - 'redis'
            - 'db'
volumes:
    db:
        driver: local
