version: '3.9'
services:
    redis:
        image: 'redis:alpine'
        ports:
            - '6379:6379'
    bot:
        build: .
        ports:
            - '8080:8080'
        depends_on:
            - 'redis'
